import {
  BarChart3,
  ChartColumn,
  FileText,
  HandCoins,
  Landmark,
  PieChart,
  Receipt,
  ReceiptText,
  ShieldCheck,
  Users,
  Wallet,
  WandSparkles,
} from "lucide-react";

export const sidebarNav = [
  {
    id: "finance",
    label: "Finance",
    icon: Wallet,
    path: "/finance",
    hasChildren: false,
    children: [],
  },
  {
    id: "sales-crm",
    label: "Sales CRM",
    icon: PieChart,
    path: "/sales-crm",
    hasChildren: false,
    children: [],
  },
  {
    id: "rms",
    label: "RMS",
    icon: Landmark,
    path: "/rms",
    hasChildren: true,
    children: [
      {
        id: "rms-dashboard",
        parentId: "rms",
        label: "Dashboard",
        icon: ChartColumn,
        path: "/rms/dashboard",
        hasChildren: false,
        children: [],
      },
      {
        id: "rms-disbursement",
        parentId: "rms",
        label: "Disbursement",
        icon: HandCoins,
        path: "/rms/disbursement",
        hasChildren: false,
        children: [],
      },
      {
        id: "rms-invoices",
        parentId: "rms",
        label: "Invoices",
        icon: Receipt,
        path: "/rms/invoices",
        hasChildren: false,
        children: [],
      },
      {
        id: "rms-po",
        parentId: "rms",
        label: "PO",
        icon: ReceiptText,
        path: "/rms/po",
        hasChildren: false,
        children: [],
      },
      {
        id: "rms-reports",
        parentId: "rms",
        label: "RMS Reports",
        icon: BarChart3,
        path: "/rms/reports",
        hasChildren: false,
        children: [],
      },
    ],
  },
  {
    id: "compliance",
    label: "Compliance",
    icon: ShieldCheck,
    path: "/compliance",
    hasChildren: true,
    children: [
      {
        id: "compliance-dashboard",
        parentId: "compliance",
        label: "Dashboard",
        icon: ChartColumn,
        path: "/compliance/dashboard",
        hasChildren: false,
        children: [],
      },
      {
        id: "compliance-disbursement",
        parentId: "compliance",
        label: "Disbursement",
        icon: HandCoins,
        path: "/compliance/disbursement",
        hasChildren: false,
        children: [],
      },
      {
        id: "compliance-invoices",
        parentId: "compliance",
        label: "Invoices",
        icon: Receipt,
        path: "/compliance/invoices",
        hasChildren: false,
        children: [],
      },
      {
        id: "compliance-po",
        parentId: "compliance",
        label: "PO",
        icon: ReceiptText,
        path: "/compliance/po",
        hasChildren: false,
        children: [],
      },
      {
        id: "compliance-reports",
        parentId: "compliance",
        label: "Compliance Reports",
        icon: BarChart3,
        path: "/compliance/reports",
        hasChildren: false,
        children: [],
      },
    ],
  },
  {
    id: "vendors",
    label: "Vendors",
    icon: Users,
    path: "/vendors",
    hasChildren: false,
    children: [],
  },
  {
    id: "ai-suite",
    label: "AI Suite",
    icon: WandSparkles,
    path: "/ai-suite",
    hasChildren: false,
    children: [],
  },
  {
    id: "reports",
    label: "Reports",
    icon: FileText,
    path: "/reports",
    hasChildren: false,
    children: [],
  },
];